export const NAME_SEARCH_COMMITTEE_REQUEST = 'NAME_SEARCH_COMMITTEE_REQUEST';
export const NAME_SEARCH_COMMITTEE_SUCCESS = 'NAME_SEARCH_COMMITTEE_SUCCESS';
export const NAME_SEARCH_COMMITTEE_FAILURE = 'NAME_SEARCH_COMMITTEE_FAILURE';

export const NAME_SEARCH_CANDIDATE_REQUEST = 'NAME_SEARCH_CANDIDATE_REQUEST';
export const NAME_SEARCH_CANDIDATE_SUCCESS = 'NAME_SEARCH_CANDIDATE_SUCCESS';
export const NAME_SEARCH_CANDIDATE_FAILURE = 'NAME_SEARCH_CANDIDATE_FAILURE';

export const SECTION_E_BY_CANDIDATE_REQUEST = 'SECTION_E_BY_CANDIDATE_REQUEST';
export const SECTION_E_BY_CANDIDATE_SUCCESSS = 'SECTION_E_BY_CANDIDATE_SUCCESSS';
export const SECTION_E_BY_CANDIDATE_FAILURE = 'SECTION_E_BY_CANDIDATE_FAILURE';

export const SECTION_E_BY_COMMITTEE_REQUEST = 'SECTION_E_BY_COMMITTEE_REQUEST';
export const SECTION_E_BY_COMMITTEE_SUCCESSS = 'SECTION_E_BY_COMMITTEE_SUCCESSS';
export const SECTION_E_BY_COMMITTEE_FAILURE = 'SECTION_E_BY_COMMITTEE_FAILURE';

export const SECTION_E_RELATIONSHIP_HISTORY_REQUEST = 'SECTION_E_RELATIONSHIP_HISTORY_REQUEST';
export const SECTION_E_RELATIONSHIP_HISTORY_SUCCESS = 'SECTION_E_RELATIONSHIP_HISTORY_SUCCESS';
export const SECTION_E_RELATIONSHIP_HISTORY_FAILURE = 'SECTION_E_RELATIONSHIP_HISTORY_FAILURE';

export const SWITCH_MODE = 'SWITCH_MODE';
