
export const NAME_SEARCH_COMMITTEE_SUCCESS = 'NAME_SEARCH_COMMITTEE_SUCCESS';
export const NAME_SEARCH_COMMITTEE_FAILURE = 'NAME_SEARCH_COMMITTEE_FAILURE';


export const NAME_SEARCH_CANDIDATE_SUCCESS = 'NAME_SEARCH_CANDIDATE_SUCCESS';
export const NAME_SEARCH_CANDIDATE_FAILURE = 'NAME_SEARCH_CANDIDATE_FAILURE';


export const COMMITTEES_BY_CANDIDATE_SUCCESS = 'COMMITTEES_BY_CANDIDATE_SUCCESS';
export const COMMITTEES_BY_CANDIDATE_FAILURE = 'COMMITTEES_BY_CANDIDATE_FAILURE';

export const CANDIDATES_BY_COMMITTEE_SUCCESS = 'CANDIDATES_BY_COMMITTEE_SUCCESS';
export const CANDIDATES_BY_COMMITTEE_FAILURE = 'CANDIDATES_BY_COMMITTEE_FAILURE';


export const SCHEDULE_ES_BY_COMMITTEE_SUCCESSS = 'SCHEDULE_ES_BY_COMMITTEE_SUCCESSS';
export const SCHEDULE_ES_BY_COMMITTEE_FAILURE = 'SCHEDULE_ES_BY_COMMITTEE_FAILURE';


export const SCHEDULE_ES_BY_CANDIDATE_SUCCESSS = 'SCHEDULE_ES_BY_CANDIDATE_SUCCESSS';
export const SCHEDULE_ES_BY_CANDIDATE_FAILURE = 'SCHEDULE_ES_BY_CANDIDATE_FAILURE';

export const SWITCH_MODE = 'SWITCH_MODE';

export const UPDATE_CANDIDATE_INPUT = 'UPDATE_CANDIDATE_INPUT';
export const UPDATE_COMMITTEE_INPUT = 'UPDATE_COMMITTEE_INPUT';
